### ISSUE TITLE
Unable to install latest version of FormBuilderImagePicker

### ISSUE THREAD

**Issue by ExpertKiD** [flutter-form-builder-ecosystem/form_builder_image_picker#34]
## Environment

**Package version:**  

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-US)
    • Flutter version 3.0.5 at /Users/expertkid/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/expertkid/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/expertkid/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • M2102J20SG (mobile) • 6f68371c • android-arm64  • Android 12 (API 31)
    • macOS (desktop)     • macos    • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 104.0.5112.79
    ! Error: nitv’s iPhone is not connected. Xcode will continue when nitv’s iPhone is connected. (code -13)
    ! Error: Suman’s iPhone is not connected. Xcode will continue when Suman’s iPhone is connected. (code -13)
    ! Error: iPhone 7 is not connected. Xcode will continue when iPhone 7 is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

<details>
  <summary>pubspec.dev</summary>

```yaml
name: app
description: Write your flutter project description here.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # localization
  intl: ^0.17.0

  # firebase
  firebase_core: ^1.12.0
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  cloud_functions: ^3.3.3
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.5.3
  firebase_dynamic_links: ^4.1.1
  firebase_in_app_messaging: ^0.6.0+9
  firebase_app_installations: ^0.1.0+8
  firebase_performance: ^0.8.0+7
  firebase_database: ^9.1.0
  firebase_remote_config: ^2.0.2

  # social logins
  google_sign_in: ^5.4.0
  flutter_facebook_auth: ^4.4.0
  sign_in_with_apple: ^4.1.0

  # crypto - for apple sign in
  crypto: ^3.0.1

  # local notifications
  flutter_local_notifications: ^9.7.0

  # annotations
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0

  # Equatable
  equatable: ^2.0.3

  # bloc
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0

  # auto routes
  auto_route: ^4.2.1

  # dio
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_hive_store: ^3.1.1

  # hive
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # functional programming
  dartz: ^0.10.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # responsive ui builder
  responsive_builder: ^0.4.2

  # widgets
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.1
  webview_flutter: ^3.0.4
  shimmer: ^2.0.0

  # native splash screens
  flutter_native_splash: ^2.2.7

  # url launcher
  url_launcher: ^6.1.5

  # media players
  video_player: ^2.4.5
  audioplayers: ^1.0.1

  # svg support
  flutter_svg: ^1.1.1+1

  # permissions
  permission_handler: ^10.0.0

  # secure local storage
  flutter_secure_storage: ^5.0.2

  # dependency_injections
  get_it: ^7.2.0
  injectable: ^1.5.3

  # plus packages
  package_info_plus: ^1.4.2
  device_info_plus: ^4.0.0

  # connectivity test
  internet_connection_checker: ^0.0.1+4

  # location
  geolocator: ^9.0.1

  # device preview
  device_preview: ^1.1.0

  # payments
  flutter_stripe: ^4.0.0
  pay: ^1.0.10
  in_app_purchase: ^3.0.6

  # fonts
  google_fonts: ^3.0.1

  # forms
  flutter_form_builder: ^7.5.0
  form_builder_validators: ^8.3.0
  form_builder_image_picker: ^3.1.0

  # input formatters
  flutter_multi_formatter: ^2.6.0

  # maths
  vector_math: ^2.1.2

  # async
  async: ^2.8.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # test
  test: ^1.20.2

  # bloc test
  bloc_test: ^9.0.3

  # mocktail
  mocktail: ^0.3.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

  # freezed
  freezed: ^2.1.0+1

  # json serialization
  json_serializable: ^6.3.1

  # generators
  injectable_generator: ^1.5.4
  auto_route_generator: ^4.2.0

  # build runner
  build_runner: ^2.1.8



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/splash-v31/
    - assets/images/logos/
    - assets/svgs/
    - assets/svgs/logos/
    - assets/svgs/icons/
    - fonts/poppins/
    - fonts/proxima-nova/
    - configs/

  fonts:
    - family: "Proxinova"
      fonts:
        - asset: fonts/proxima-nova/proximanova-black.otf
          weight: 900
        - asset: fonts/proxima-nova/proximanova-blackit.otf
          style: italic
          weight: 900
        - asset: fonts/proxima-nova/proximanova-bold.otf
          weight: 700
        - asset: fonts/proxima-nova/proximanova-boldit.otf
          weight: 700
          style: italic
        - asset: fonts/proxima-nova/proximanova-extrabold.otf
          weight: 800
        - asset: fonts/proxima-nova/proximanova-extraboldit.otf
          weight: 800
          style: italic
        - asset: fonts/proxima-nova/proximanova-light.otf
          weight: 300
        - asset: fonts/proxima-nova/proximanova-lightit.otf
          weight: 300
          style: italic
        - asset: fonts/proxima-nova/proximanova-medium.otf
          weight: 500
        - asset: fonts/proxima-nova/proximanova-mediumit.otf
          weight: 500
          style: italic
        - asset: fonts/proxima-nova/proximanova-regular.otf
        - asset: fonts/proxima-nova/proximanova-regularit.otf
          style: italic
        - asset: fonts/proxima-nova/proximanova-semibold.otf
          weight: 600
        - asset: fonts/proxima-nova/proximanova-semiboldit.otf
          weight: 600
          style: italic
        - asset: fonts/proxima-nova/proximanova-thin.otf
          weight: 100
        - asset: fonts/proxima-nova/proximanova-thinit.otf
          weight: 100
          style: italic




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

## Description

**Expected behavior:**
Expected the package to install.

**Current behavior:**
```bash
Because every version of integration_test from sdk depends on async 2.8.2 and form_builder_image_picker >=3.0.0 depends on async ^2.9.0, integration_test from sdk is incompatible with form_builder_image_picker >=3.0.0.
So, because app depends on both form_builder_image_picker ^3.0.0 and integration_test from sdk, version solving failed.
pub get failed (1; So, because app depends on both form_builder_image_picker ^3.0.0 and integration_test from sdk, version solving failed.)
```

It's not just the integration test. All test packages give the same error.

## Steps to reproduce

1. Copy pubspec.yaml 
2. Hit `pub get`
